### ISSUE TITLE
Could you add photos of the pins used?

### ISSUE THREAD

**Issue by ogg1e** [mbtaylor1982/A3000-Agnus-Adapter#1]
I'm not sure what type of header pins to use on the bottom side of this.   Could you add a description and/or photo? Or a mouser link to them?

I think you also might want to add the plcc84 socket to the list as well.  This should be the correct one:
https://www.mouser.com/ProductDetail/3M-Electronic-Solutions-Division/8484-11B1-RK-TP?qs=WZRMhwwaLl9eNFJXLRGlFw==

**Comment by mbtaylor1982** [comment]
These are the pins I use, I actually tack them in from the top side of the board before adding the PLCC socket.
![image](https://user-images.githubusercontent.com/1866358/171028505-7e6b1361-ca3b-45b4-9708-22ddc5fa3463.png)

after soldering the socket a solder the next rows of header pins and slide the black plastic back down after soldering them in from the underside.

**Comment by olDirdey** [comment]
in terms of time it´s cheaper just to buy a 8372b than soldering this thing

![](https://abload.de/img/mobile.14421yesn.jpeg) ![](https://abload.de/img/mobile.144339imd.jpeg) ![](https://abload.de/img/mobile.1448tnfqk.jpeg)

**Comment by mbtaylor1982** [comment]
@olDirdey yeah I admit it is not the easiest project to solder but it's compact and you can fit it to the board and still use the bottom Zorro slot on the riser card.

**Comment by mbtaylor1982** [comment]
Pin headers and socket are now added to the BOM in Readme.md
