### ISSUE TITLE
A2000 compatibility?

### ISSUE THREAD

**Issue by DoctorDan1986** [mbtaylor1982/A3000-Agnus-Adapter#2]
Can anyone confirm compatibility with an Amiga 2000?  I'm not certain if the pinout for the 3000 AGNUS differs from the 2000.

**Comment by mbtaylor1982** [comment]
@DoctorDan1986  The pinout for the A2000 and A3000 are different [Pinouts](https://en.wikipedia.org/wiki/MOS_Technology_Agnus#PLCC_Versions)

There is no need to use this adaptor in the A2000 as the compatible Agnus chips can be found easily on Ebay etc...
the Adaptor is designed to allow the use of the A500+/A600 Agnus with the A3000, 

If you are looking for the 2MB Agnus adaptor for the A2000 try this project https://github.com/LIV2/A500-2Meg-Chip-ram

**Comment by DoctorDan1986** [comment]
> @DoctorDan1986 The pinout for the A2000 and A3000 are different [Pinouts](https://en.wikipedia.org/wiki/MOS_Technology_Agnus#PLCC_Versions)
> 
> There is no need to use this adaptor in the A2000 as the compatible Agnus chips can be found easily on Ebay etc... the Adaptor is designed to allow the use of the A500+/A600 Agnus with the A3000,
> 
> If you are looking for the 2MB Agnus adaptor for the A2000 try this project https://github.com/LIV2/A500-2Meg-Chip-ram

PAL models, sure.  But I have an NTSC system.  I don't think I can just drop a 390544-01 into an NTSC A2000.  (Corrected mistype)

**Comment by mbtaylor1982** [comment]
@DoctorDan1986  I assume you mean 390544-01 in your comment, if so you are correct these are PAL specific. you will need the 390544-02 NTSC Fat Agnus with the https://github.com/LIV2/A500-2Meg-Chip-ram project for and NTSC machine.

**Comment by DoctorDan1986** [comment]
> @DoctorDan1986 I assume you mean 390544-01 in your comment, if so you are correct these are PAL specific. you will need the 390544-02 NTSC Fat Agnus with the https://github.com/LIV2/A500-2Meg-Chip-ram project for and NTSC machine.

I'm reading that a PAL 318069-xx AGNUS can work on an NTSC Amiga?

https://eab.abime.net/showthread.php?t=92402
