### ISSUE TITLE
Compatibility with an NTSC 318069?

### ISSUE THREAD

**Issue by ogg1e** [mbtaylor1982/A3000-Agnus-Adapter#3]
Do we know if we can use a VBB 318069-11 agnus with this?

**Comment by mbtaylor1982** [comment]
Provision has been Made for Vbb on pin 40 (**C14M**). 

When using one of the below parts marked Vbb **C2** should be populated with a 0.1uF ceramic capacitor.  

**_Please note i do not have one of these chips so have not been able to test it._**

> **318069-10** 
> Several pins have been changed to support the A600. This device supports PAL only - the PAL/_NTSC pad is internally  pulled up to Vdd (+5). This part is the new rev of what was previously called **390554-01**, except that Vbb replaces the **C14M** pin.
> 
>  **318069-11** 
> This pinout is identical to the -10. However, this device supports NTSC only - the PAL/_NTSC pad is internally connected to GND. This part is the new rev of what was previously called **390554-02**, except that Vbb replaces the **C14M** pin.
> 
>  **318069-12** 
> Several pins have been changed to support the A600.  This device supports PAL only - the PAL/_NTSC pad is internally pulled up to Vdd (+5). This part is the new rev of what was previously called **390554-01**.
> 
>  **318069-13** 
> Several pins have been changed to support the A600. This device supports NTSC only - the PAL/_NTSC pad is internally connected to ground. This part is the new rev of what was previously called **390554-02**.
> 

Source of above info > [https://www.amigawiki.org/lib/exe/fetch.php?media=de:parts:agnus-history.pdf](https://www.amigawiki.org/lib/exe/fetch.php?media=de:parts:agnus-history.pdf)
